spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      routes:
        - id: vets-service
          uri: https://asa-demo-vets-service.azuremicroservices.io
          predicates:
            - Path=/api/vet/**
          filters:
            - StripPrefix=2
        - id: visits-service
          uri: https://asa-demo-visits-service.azuremicroservices.io
          predicates:
            - Path=/api/visit/**
          filters:
            - StripPrefix=2
        - id: customers-service
          uri: https://asa-demo-customers-service.azuremicroservices.io
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2

# from https://github.com/Azure-Samples/spring-petclinic-microservices-config/blob/master/api-gateway.yml
zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    vets-service: /vet/**
    visits-service: /visit/**
    customers-service: /customer/**
    api-gateway: /gateway/**

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript
    min-response-size: 2048

# Internationalization
spring.messages.basename: messages/messages
